site_name: Django-jsonrpc
theme: material

nav:
  - Home: index.md 
  - Authentication: authentication.md
  - How_To:
    - Create a method: create_method.md
    - Include a controller: include_controller.md
    - Custom error: custom_error.md
    - OpenRPC: openrpc.md
    - Streaming: streaming.md